### ISSUE TITLE
Unhandled exception

### ISSUE THREAD

**Issue by probonopd** [exitbgmbh/logmodmobile-electron#4]
Hi, thanks for making an AppImage. Unfortunately it gives an unhandled exception while trying to run on Ubuntu xenial:

```
setupConfig::checkConfig::start

setupConfig::checkConfig::configuration path set /home/travis/.config/logmodmobile-electron

preCheckConfig::setupConfig::could not find configuration path. setting up...

preCheckConfig::setupConfig::start

setupConfig::setupConfig::/run/firejail/appimage/.appimage-9316/config/default.dist.json

setupConfig::setupConfig::/home/travis/.config/logmodmobile-electron/default.json

A JavaScript error occurred in the main process

Uncaught Exception:

Error: ENOENT: no such file or directory, copyfile '/run/firejail/appimage/.appimage-9316/config/default.dist.json' -> '/home/travis/.config/logmodmobile-electron/default.json'

    at Object.copyFileSync (fs.js:1731:3)

    at Object.func (electron/js2c/asar.js:140:31)

    at Object.func [as copyFileSync] (electron/js2c/asar.js:140:31)

    at setupConfig (/run/firejail/appimage/.appimage-9316/resources/app.asar/setupConfig.js:46:15)

    at checkConfig (/run/firejail/appimage/.appimage-9316/resources/app.asar/setupConfig.js:61:9)

    at Object.<anonymous> (/run/firejail/appimage/.appimage-9316/resources/app.asar/index.js:5:5)

    at Module._compile (internal/modules/cjs/loader.js:880:30)

    at Object.Module._extensions..js (internal/modules/cjs/loader.js:892:10)

    at Module.load (internal/modules/cjs/loader.js:735:32)

    at Module._load (internal/modules/cjs/loader.js:648:12)

0x200003 "logmodmobile-electron": ("logmodmobile-electron" "Logmodmobile-electron")  200x200+0+0  +0+0

0x200001 "logmodmobile-electron": ("logmodmobile-electron" "Logmodmobile-electron")  10x10+10+10  +10+10

NUMBER_OF_WINDOWS: 2

IceWM: using /home/travis/.icewm for private configuration files

convert: unable to read X window image `0xa00011': Resource temporarily unavailable @ error/xwindow.c/XImportImage/5005.

convert: no images defined `database/LogModMobile/screenshot.png' @ error/convert.c/ConvertImageCommand/3210.
```

Reference:
https://github.com/AppImage/appimage.github.io/pull/2264

**Comment by ccarnivore** [comment]
Hi @probonopd ,

thanks for reporting the issue.
its fixed with commit 88ced7d917a6215bb97527aac2fd1dcbd1f38e4e
